
public class Exececao {

	public static void main(String[] args) {
		
	try {
		int resultado = 10/2;
		System.out.println(resultado);
	}
	catch(Exception e){
		System.out.println("Erro: " + e.getMessage());
	}
	
		
		
	}

}
